### ISSUE TITLE
Error: "File 'sensor_fusion_pkg_launch.py' was not found..."

### ISSUE THREAD

**Issue by jbnunn** [aws-deepracer/aws-deepracer-sensor-fusion-pkg#3]
While following the steps in README and launching the sensor_fusion_node with `ros2 launch sensor_fusion_pkg sensor_fusion_pkg_launch.py` I get the following error:

```
file 'sensor_fusion_pkg_launch.py' was not found in the share directory of package 'sensor_fusion_pkg' which is at '/root/deepracer_ws/aws-deepracer-sensor-fusion-pkg/install/sensor_fusion_pkg/share/sensor_fusion_pkg'
```

**Comment by siddalingesha-ds** [comment]
Hi,

Thank you for reporting the issue. We have updated the README file with the right launch file name.

` ros2 launch sensor_fusion_pkg sensor_fusion_launch.py`

**Comment by jbnunn** [comment]
I tried that as well, but no luck. I get the error `...file 'sensor_fusion_launch.py' was not found...`. It doesn't appear that file is in the install directory at all, only in the launch directory.

```
root@amss-36kh:~/deepracer_ws/aws-deepracer-sensor-fusion-pkg# find . -name '*.py' | grep 'sensor_fusion_launch.py'
./sensor_fusion_pkg/launch/sensor_fusion_launch.py
```

Is there an XML file that needs to be updated with the new name?

**Comment by pratik-nichat** [comment]
Hello @jbnunn,
Thank you for reporting the issue. We have fixed the issue in our latest [commit](https://github.com/aws-deepracer/aws-deepracer-sensor-fusion-pkg/commit/bf7b9d0dd789a0c6e6713eaeee8d2300adb578af) and verified the independent [launch](https://github.com/aws-deepracer/aws-deepracer-sensor-fusion-pkg#run-the-node) of sensor fusion node. Please let us know if you have more questions.
